// Component exports
export { default as VisionCard } from './onboarding/VisionCard'
export { default as FigmaVisionBuilder } from './onboarding/FigmaVisionBuilder'
export { default as TimeSlider } from './time-budget/TimeSlider'
export { default as TimeAllocationCard } from './time-budget/TimeAllocationCard'
export { TimebudgetDashboard } from './time-budget/TimebudgetDashboard'
export { default as FigmaTimeBudget } from './time-budget/FigmaTimeBudget'
export { default as ActionCard } from './daily-actions/ActionCard'
export { default as EnhancedActionCard } from './daily-actions/EnhancedActionCard'
export { DailyActionsDashboard } from './daily-actions/DailyActionsDashboard'
export { DailyProgressSummary } from './daily-actions/DailyProgressSummary'
export { default as FigmaActionsPage } from './daily-actions/FigmaActionsPage'
export { default as Timer } from './timer/Timer'
export { default as Trophy } from './victory/Trophy'
export { default as FigmaVictoryScreen } from './victory/FigmaVictoryScreen'
export { default as FigmaCommunityPage } from './community/FigmaCommunityPage'
export { default as FigmaProfilePage } from './profile/FigmaProfilePage'
export { default as FigmaDashboard } from './dashboard/FigmaDashboard'